### ISSUE TITLE
HTTP error pushing Go example from local

### ISSUE THREAD

**Issue by brett-earle-notitia** [mondaycom/monday-apps-cli#84]
``` mapps code:push --verbose --print-command
[15:11:25.077] DEBUG: * Domain: https://monday-apps-ms.monday.com *
[15:11:26.075] DEBUG: api_service
    res: GET: https://monday-apps-ms.monday.com/api/apps - 200
? Select an app 10131502 | New App
[15:11:34.737] DEBUG: api_service
    res: GET: https://monday-apps-ms.monday.com/api/apps/10131502/versions - 200
? Select an app version 10201446 | 1.0.0 | New App |
 draft
[15:11:38.095] DEBUG: push code to appVersionId: 10201446
⠋ Build asset to deploy
[15:11:38.127] DEBUG: Directory path not provided. using current directory: /Users/brett/work_projects/m
⠋ Build asset to deploy
  › Building asset to deploy from
    "/Users/brett/work_projects/monday-code-quicksta
    rts/quickstart-go" directory
[15:11:38.128] DEBUG: create_archive - Check directory exists
    directoryPath: "/Users/brett/work_projects/monday-code-quickstarts/quickstart-go"
[15:11:38.129] DEBUG: ignore_files_for_archive - Searching for .mappsignore file
[15:11:38.130] DEBUG: ignore_files_for_archive - Searching for .gitignore file
[15:11:38.131] DEBUG: ignore_files_for_archive - No ignore files found, you can use .gitignore or
    .mappsignore to exclude some of the folders and files in your project
[15:11:38.131] DEBUG: archive - Starting
    directoryPath: "/Users/brett/work_projects/monday-code-quickstarts/quickstart-go"
    archivePath: "/Users/brett/work_projects/monday-code-quickstarts/quickstart-go/code.tar.gz"
[15:11:38.133] DEBUG: archive - Initialized
[15:11:38.133] DEBUG: archive - Added paths to ignore
    0: "/Users/brett/work_projects/monday-code-quickstarts/quickstart-go/code.tar.gz"
    1: "**/code.tar.gz"
    2: ".git/**"
    3: ".env"
    4: "local-secure-storage.db.json"
✔ Build asset to deploy
⠏ Preparing environment
[15:11:48.150] ERROR: get_signed_storage_url
    err: {
      "type": "HttpError",
      "message": "Unexpected error occurred while communicating with the remote server",
      "stack":
          Error: Unexpected error occurred while communicating with the remote server
              at handleErrors (file:///opt/homebrew/lib/node_modules/@mondaycom/apps-cli/dist/services/api-service.js:50:15)
              at execute (file:///opt/homebrew/lib/node_modules/@mondaycom/apps-cli/dist/services/api-service.js:91:16)
              at async getSignedStorageUrl (file:///opt/homebrew/lib/node_modules/@mondaycom/apps-cli/dist/services/push-service.js:22:26)
              at async _Task.prepareEnvironmentTask [as taskFn] (file:///opt/homebrew/lib/node_modules/@mondaycom/apps-cli/dist/services/push-service.js:139:39)
              at async _Task.run (file:///opt/homebrew/lib/node_modules/@mondaycom/apps-cli/node_modules/listr2/dist/index.js:1965:11)
✔ Build asset to deploy
✖ Unexpected error occurred while communicating
  with the remote server
[15:11:48.153] ERROR: code_push
    err: {
      "type": "HttpError",
      "message": "Unexpected error occurred while communicating with the remote server",
      "stack":
          Error: Unexpected error occurred while communicating with the remote server
              at handleErrors (file:///opt/homebrew/lib/node_modules/@mondaycom/apps-cli/dist/services/api-service.js:50:15)
              at execute (file:///opt/homebrew/lib/node_modules/@mondaycom/apps-cli/dist/services/api-service.js:91:16)
              at async getSignedStorageUrl (file:///opt/homebrew/lib/node_modules/@mondaycom/apps-cli/dist/services/push-service.js:22:26)
              at async _Task.prepareEnvironmentTask [as taskFn] (file:///opt/homebrew/lib/node_modules/@mondaycom/apps-cli/dist/services/push-service.js:139:39)
              at async _Task.run (file:///opt/homebrew/lib/node_modules/@mondaycom/apps-cli/node_modules/listr2/dist/index.js:1965:11)
      "description": "An error."
    } 
```
Hey all,
I have run MAPPS init and put in my api key. Have cloned the go project. Made a app and installed cli. Ran push command and getting error above. From the go hello world run on defaults, no env added.

**Comment by gregra81** [comment]
Hey @brett-earle-notitia, sorry for that.

I just deployed a fresh project based on the go template https://github.com/mondaycom/monday-code-quickstarts/tree/main/quickstart-go and app was deployed successfully, can you please try again?

Greg

**Comment by brett-earle-notitia** [comment]
All good, will do, currently just building it locally and using api instead
of having it deployed on Monday code for now. Will let you know how it goes

Brett Earle

Software Developer

Book a meeting with me <https://meetings.hubspot.com/brett-earle>
0458 733 650 <+61458733650>
***@***.***
www.notitia.consulting
Level 3, 12 Pirie St, Adelaide SA 5000
[image: linkedin] <https://www.linkedin.com/in/brettearle/>

**Comment by brett-earle-notitia** [comment]
All good thanks Greg. Will give it a shot in the coming week.
